# Updates the page repository (with a pull request) when this repository's main branch changes
name: Update page

on:
    # Trigger when there are new commits to the main branch
    push:
        branches:
            - main

jobs:
    update:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  repository: 'inf-lab-dev/page'
                  ref: main
                  submodules: 'recursive'
                  fetch-depth: 0
                  token: ${{ secrets.SYNC_TOKEN }}

            - name: Update git user
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"

            # Update submodule in page repository
            - name: Update Content
              run: |
                  git submodule update --remote --merge
                  git add .
                  git commit -m "Update content to latest commit from `labs/main@${{ github.sha }}`"

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v7
              with:
                  token: ${{ secrets.SYNC_TOKEN }}
                  delete-branch: true
                  author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
                  branch: 'update-content/${{ github.sha }}'
                  title: 'Update content to ${{ github.sha }}'
                  base: main
                  body: |
                      The content has been updated to the latest commit ${{ github.repository }}@${{ github.sha }} from the [labs](https://github.com/inf-lab-dev/labs) repository.
